### ISSUE TITLE
Update Metadata

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#5]
- [ ] Add (localized) app screenshots
- [x] Add app icon
- [x] Add feature graphic
- [x] Create a trailer
- [x] Add changelogs
- [x] Add custom Open Graph [image](https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/)

**Comment by CrazyMarvin** [comment]
Added app icon, feature graphic and custom Open Graph image for GitHub ✅

**Comment by CrazyMarvin** [comment]
Uploaded [trailer](https://youtu.be/_UStlpEMVro) to YouTube
